name: Duplicate Issue
description: Creates a full copy of issue with a single command.
author: bubkoo <bubkoo.wy@gmail.com>

inputs:
  GITHUB_TOKEN:
    description: Your GitHub token for authentication.
    required: true
  command:
    description: Command name to copy the issue.
    default: duplicate
    required: false
  who:
    description: Who can duplicate the issue.
    default: author
    required: false
  extras:
    description: Additional information appended to the duplicated issue body.
    default: '> This issue was copied from [#{{ issueNumber }}]({{ issueUrl }}) by @{{ author }}.'
    required: false

runs:
  using: node16
  main: dist/index.js

branding:
  icon: copy
  color: orange
